namespace EnderunAI.Api.Contracts.Isg;

public sealed record CreateIsgIncidentRequest(
    Guid CompanyId,
    Guid? ProjectId,
    Guid? ProjectSiteId,
    Guid? PersonnelId,
    DateTime IncidentDateTime,
    int IncidentType,
    int Severity,
    string Description,
    string? RootCause,
    string? ActionTaken,
    int LostWorkDays,
    bool SgkNotified,
    DateTime? SgkNotificationDate,
    string? SgkNotificationNumber);

public sealed record UpdateIsgIncidentRequest(
    Guid? ProjectId,
    Guid? ProjectSiteId,
    Guid? PersonnelId,
    DateTime IncidentDateTime,
    int IncidentType,
    int Severity,
    string Description,
    string? RootCause,
    string? ActionTaken,
    int LostWorkDays,
    bool SgkNotified,
    DateTime? SgkNotificationDate,
    string? SgkNotificationNumber,
    int Status,
    string? ClosureNote);

public sealed record IsgIncidentListItem(
    Guid Id,
    DateTime IncidentDateTime,
    int IncidentType,
    string IncidentTypeName,
    int Severity,
    string SeverityName,
    string SeverityColor,
    Guid? ProjectId,
    string? ProjectCode,
    Guid? ProjectSiteId,
    string? SiteName,
    Guid? PersonnelId,
    string? PersonnelName,
    int LostWorkDays,
    bool SgkNotified,
    /// <summary>Bildirim gerektiren ama yapılmamış kayıt.</summary>
    bool SgkNotificationOverdue,
    int Status,
    string StatusName);

public sealed record IsgIncidentDetail(
    Guid Id,
    Guid CompanyId,
    DateTime IncidentDateTime,
    int IncidentType,
    string IncidentTypeName,
    int Severity,
    string SeverityName,
    string SeverityColor,
    Guid? ProjectId,
    string? ProjectCode,
    string? ProjectName,
    Guid? ProjectSiteId,
    string? SiteName,
    Guid? PersonnelId,
    string? PersonnelName,
    string Description,
    string? RootCause,
    string? ActionTaken,
    int LostWorkDays,
    bool SgkNotified,
    DateTime? SgkNotificationDate,
    string? SgkNotificationNumber,
    bool SgkNotificationOverdue,
    int Status,
    string StatusName,
    DateTime? ClosedAtUtc,
    string? ClosureNote,
    DateTime CreatedAtUtc);
