"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import ErpShell from "@/components/erp/erp-shell";
type Company={id:string;code:string;name:string};type Branch={id:string;companyId:string;companyName:string;code:string;name:string;phone?:string;email?:string;isHeadOffice:boolean;isActive:boolean};
const blank={companyId:"",code:"",name:"",phone:"",email:"",address:"",isHeadOffice:false};
async function api(path:string,options?:RequestInit){const r=await fetch(`/api/backend/${path}`,{cache:"no-store",...options});if(r.status===401){location.href="/login";throw new Error("Oturum süresi doldu.");}const j=await r.json().catch(()=>null);if(!r.ok)throw new Error(j?.message??`Hata ${r.status}`);return j;}
export default function Page(){const [companies,setCompanies]=useState<Company[]>([]),[items,setItems]=useState<Branch[]>([]),[form,setForm]=useState(blank),[show,setShow]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
const load=useCallback(async()=>{try{const[c,b]=await Promise.all([api("companies"),api("branches")]);setCompanies(c);setItems(b);setForm(f=>({...f,companyId:f.companyId||c[0]?.id||""}));}catch(e){setErr(e instanceof Error?e.message:"Liste alınamadı.");}},[]);
useEffect(()=>{load();},[load]);async function save(e:FormEvent){e.preventDefault();try{await api("branches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setMsg("Şube oluşturuldu.");setShow(false);setForm({...blank,companyId:form.companyId});await load();}catch(x){setErr(x instanceof Error?x.message:"Kayıt başarısız.");}}
return <ErpShell design="redwood" title="Şube Yönetimi"><div className="erp-toolbar"><strong>{items.length} şube</strong><div className="erp-actions"><button type="button" onClick={()=>void load()}>Yenile</button><button onClick={()=>setShow(!show)}>+ Yeni Şube</button></div></div>{msg&&<div className="erp-alert success">{msg}</div>}{err&&<div className="erp-alert error">{err}</div>}
{show&&<form className="erp-form-card" onSubmit={save}><div className="erp-form-grid"><label className="span-2"><span>Şirket *</span><select required value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})}><option value="">Seçin</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></label><label><span>Kod *</span><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label><span>Ad *</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Telefon</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span>E-posta</span><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="span-2 erp-check"><input type="checkbox" checked={form.isHeadOffice} onChange={e=>setForm({...form,isHeadOffice:e.target.checked})}/> Merkez şube</label></div><div className="erp-actions"><button type="submit">Kaydet</button></div></form>}
<div className="erp-table-card"><table className="erp-table"><thead><tr><th>Kod</th><th>Şube</th><th>Şirket</th><th>Tür</th><th>Durum</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.name}</td><td>{x.companyName}</td><td><span className="erp-status blue">{x.isHeadOffice?"Merkez":"Şube"}</span></td><td><span className="erp-status green">{x.isActive?"Aktif":"Pasif"}</span></td></tr>)}</tbody></table></div></ErpShell>}
